---
title: "R for linguists"
subtitle: "An introduction"
author: "Joseph V. Casillas</br>Rutgers University"
date: "Last update: `r format(Sys.time(), '%D')`"
output: 
  learnr::tutorial:
    highlight: tango
    theme: cosmo
runtime: shiny_prerendered
---

```{r, echo=FALSE, cache=FALSE}
knitr::opts_chunk$set(cache=FALSE, echo=FALSE)
library(learnr)
```


```{r setup, include=FALSE}
library(tidyverse)

my_data <- tribble(
  ~'id',    ~'spec', ~'test1', ~'test2', 
   'span01', 'g1_lo',  64.31,   69.2,
   'span02', 'g1_lo',  59.81,   63.7,
   'span03', 'g1_hi',  66.08,   70.9,
   'span04', 'g1_hi',  72.78,   79.2,
   'span05', 'g2_lo',  68.29,   75.4,
   'span06', 'g2_lo',  69.22,   76.7,
   'span07', 'g2_hi',  71.36,   77.2,
   'span08', 'g2_hi',  80.37,   88.9,
   'cata01', 'g1_lo',  75.63,   83.6,
   'cata02', 'g1_lo',  71.25,   78.8,
   'cata03', 'g1_hi',  69.09,   74.6,
   'cata04', 'g1_hi',  72.35,   80.7,
   'cata05', 'g2_lo',  71.66,   77.9,
   'cata06', 'g2_lo',  69.01,   75.0,
   'cata07', 'g2_hi',  69.86,   76.0,
   'cata08', 'g2_hi',  77.34,   85.6
) 
```

```{r, child='./lessons/00_intro.Rmd'}
```

```{r, child='./lessons/01_working_directories.Rmd'}
```

```{r, child='./lessons/02_install_packages.Rmd'}
```

```{r, child='./lessons/03_load_packages.Rmd'}
```

```{r, child='./lessons/04_comments.Rmd'}
```

```{r, child='./lessons/05_r_as_a_calculator.Rmd'}
```

```{r, child='./lessons/06_assigning_variables.Rmd'}
```

```{r, child='./lessons/07_data_structures.Rmd'}
```

```{r, child='./lessons/08_dplyr.Rmd'}
```

```{r, child='./lessons/09_tidyr.Rmd', eval=TRUE}
```

```{r, child='./lessons/10_plotting.Rmd', eval=FALSE}
```

```{r, child='./lessons/11_quiz.Rmd', eval=FALSE}
```


<!-- links -->

[lingStuff]: http://www.jvcasillas.com/lingStuff/index.html
[tidyverse]: https://www.tidyverse.org
[GitHub_lingStuff]: https://github.com/jvcasillas/lingStuff
