---
title: 'R for linguists'
subtitle: ''
date: "Last updated: `r format(Sys.time(), '%B %d %Y')`"
output: 
  html_document: 
    df_print: tibble
    theme: yeti
    toc: yes
    toc_float: yes
---

```{r file-list, echo=FALSE}
# Store all folders in 'notes' directory
# Use regex to exclude anything with a '.' 
# (this gets all folders and excludes files)
folders <- dir(pattern = "^[^.]+$")

# Store number of folders
my_length <- length(folders)

# Create empty character vector to hold paths 
children <- vector("character", length = my_length)

# For loop to store paths in 'children' vector 
# Search only for .Rmd files 
for (i in 1:length(folders)) {
  
  # List .Rmd files in each folder of 'folders'
  # store output in 'children'
  children[i] <- list.files(path = folders[i], 
                            pattern = ".html", 
                            full.names = TRUE)
}

# Print children to check folders and respective paths
# print(children)
```


# Lessons

```{r, create-links, results='asis', echo=FALSE}

# Use for loop to create links to all html files
for (file in 1:length(folders)) {
  writeLines(paste0("- [", folders[file], "](", children[file], ")"))
}
```

# Links

- another list
- goes here






